//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizationsWebApplication.TcpXmlService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TcpXmlService.IXmlService")]
    public interface IXmlService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXmlService/SaveXmlFile", ReplyAction="http://tempuri.org/IXmlService/SaveXmlFileResponse")]
        void SaveXmlFile(string document, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXmlService/SaveXmlFile", ReplyAction="http://tempuri.org/IXmlService/SaveXmlFileResponse")]
        System.Threading.Tasks.Task SaveXmlFileAsync(string document, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXmlService/LoadXmlFile", ReplyAction="http://tempuri.org/IXmlService/LoadXmlFileResponse")]
        string LoadXmlFile(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXmlService/LoadXmlFile", ReplyAction="http://tempuri.org/IXmlService/LoadXmlFileResponse")]
        System.Threading.Tasks.Task<string> LoadXmlFileAsync(string fileName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IXmlServiceChannel : OrganizationsWebApplication.TcpXmlService.IXmlService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XmlServiceClient : System.ServiceModel.ClientBase<OrganizationsWebApplication.TcpXmlService.IXmlService>, OrganizationsWebApplication.TcpXmlService.IXmlService {
        
        public XmlServiceClient() {
        }
        
        public XmlServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XmlServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XmlServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XmlServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SaveXmlFile(string document, string fileName) {
            base.Channel.SaveXmlFile(document, fileName);
        }
        
        public System.Threading.Tasks.Task SaveXmlFileAsync(string document, string fileName) {
            return base.Channel.SaveXmlFileAsync(document, fileName);
        }
        
        public string LoadXmlFile(string fileName) {
            return base.Channel.LoadXmlFile(fileName);
        }
        
        public System.Threading.Tasks.Task<string> LoadXmlFileAsync(string fileName) {
            return base.Channel.LoadXmlFileAsync(fileName);
        }
    }
}
